application: tumblrdbss
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  secure: always
  static_dir: static/

- url: /auth
  secure: always
  login: required
  script: tds.app

- url: /token
  secure: always
  script: tds.app

- url: /verify
  secure: always
  login: required
  script: tds.app

- url: /setup
  secure: always
  script: tds.app

- url: /
  secure: always
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"
