application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: static/

- url: /auth
  script: tds.app

- url: /token
  script: tds.app

- url: /verify
  script: tds.app

- url: /setup
  script: tds.app

- url: /
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"
